### ISSUE TITLE
Mark as DEPRECATED / ARCHIVE or move the W3C CCG

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/lds-merkleproof2017#6]
@msporny @kimdhamilton @davidlj95 As the only 3 contributors you are responsible for marking this repo as deprecated or moving it to the CCG.

**Comment by OR13** [comment]
If no response is provided in 1 month, this repo should be archived.

**Comment by davidlj95** [comment]
AFAIK we have to move this as it's what it is being used to add signatures in [Blockcerts](https://blockcerts.org) v2 certificates. 

For v3 I think they'll use https://github.com/w3c-dvcg/lds-merkle-proof-2019 so that should be moved too (I saw there's some discussion there already!)

**Comment by OR13** [comment]
@davidlj95 I'm happy to help move it to the ccg (I now have permission to do so). Do I have your permission to move both as was done with: https://github.com/w3c-dvcg/ld-proofs ?

**Comment by davidlj95** [comment]
I'd move it, yeah, sure! 

BTW: I don't know if I have the right to decide upon this as I'm not a member of the W3C, just a random contributor.

**Comment by OR13** [comment]
I have moved this.
